### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by nathan-c** [GoogleCloudPlatform/google-cloud-dotnet-powerpack#28]
I realise this repo is in limbo at the moment pending the work described in https://github.com/GoogleCloudPlatform/google-cloud-dotnet-powerpack/issues/24#issuecomment-975386150, however, since the main libs have been updated to GAX 4 we can no longer use this library along side the newer libs depending on GAX 4.

We see the following error when trying to decrypt
```
System.MissingMethodException: Method not found: 'Void Google.Cloud.Storage.V1.StorageClient.DownloadObject(System.String, System.String, System.IO.Stream, Google.Cloud.Storage.V1.DownloadObjectOptions, System.IProgress`1<Google.Apis.Download.IDownloadProgress>)'.
   at Google.Cloud.AspNetCore.DataProtection.Storage.CloudStorageXmlRepository.LoadLatestNoRetry(LoadDocumentResult previous)
   at Google.Cloud.AspNetCore.DataProtection.Storage.CloudStorageXmlRepository.<>c__DisplayClass10_0.<LoadLatest>b__0()
   at Google.Cloud.AspNetCore.DataProtection.Storage.RetryHandler.ExecuteWithRetry[T](Func`1 func)
   at Google.Cloud.AspNetCore.DataProtection.Storage.CloudStorageXmlRepository.LoadLatest()
   at Google.Cloud.AspNetCore.DataProtection.Storage.CloudStorageXmlRepository.GetAllElements()
```

Is there any chance a new alpha version of the libs can be released with upgraded dependencies?

**Comment by amanda-tarafa** [comment]
We'll discuss this internally and check if there's extra work we'd need to do to get these working with GAX V4.

**Comment by jskeet** [comment]
I've just published 1.0.0-alpha04 versions of both of the Data Protection libraries, which should solve this problem.
This is expected to be the last release of those packages in their current form; we plan to migrate the functionality to the google-cloud-dotnet repo, *possibly* using different GCP services, and almost certainly renaming the packages. Please follow #24 for updates.
